### ISSUE TITLE
JAVASCRIPT: venue map

### ISSUE THREAD

**Issue by shannonfromomaha** [omahacodeschool/lincoln-calling#159]
when you select a venue, the pin on the map should get bigger
and the info in the sidebar should change to that venue's information
and the schedule should show only that venue's info

**Comment by maedae** [comment]
-[ ] We still need tables with band data, 3 tabs for each day
-[ ] BONUS: focus on closest day/time based on user computer's current time

- [ ] Markers need class or id data linking it to venue in DB in order to query info (XHR in JS)
- [ ] VENUE info/image should pipe in via XHR/JQUERY. Destroy when other marker is clicked (JS)
