### ISSUE TITLE
Remove Latitude and Longitude from Venue schema - DO NOT DO THIS

### ISSUE THREAD

**Issue by shannonfromomaha** [omahacodeschool/lincoln-calling#192]
now that we're mapping addresses into the Google API these are unnecessary.
Also while you're in there, change the seed data on the seed venues to be those actual places' actual addresses

**Comment by maedae** [comment]
We actually do need the longitude and latitude columns, as they are auto-popuplated by geocoder. I already took things out of the administrate forms and changed the wording. The seed even works because I just renamed the pre-existing columns.

If you're wanting this is seed data, it will have to be done by hand still.
